### ISSUE TITLE
more than 50 devices not imported

### ISSUE THREAD

**Issue by axlroden** [AAbouZaid/netbox-as-ansible-inventory#13]
You are not paginating results from the API.

I can force more than 50 devices with ?limit=10000

But you should really do multiple queries for huge sites.

**Comment by aabouzaid** [comment]
Fixed in [v1.0.9](https://github.com/AAbouZaid/netbox-as-ansible-inventory/commit/8963572df741088fc2eb8be2438ca332ad6a6229) with commit [978d38e](https://github.com/AAbouZaid/netbox-as-ansible-inventory/commit/978d38e2d4f4226580770851c9fe077c863c7e7e).

@axlroden Could you please confirm it works as expected?

**Comment by kaplun** [comment]
@AAbouZaid just a suggestion: You might want to use pynetbox, to take care for you about pagination and interaction with netbox in general.

**Comment by axlroden** [comment]
sorry for late reply, works flawlessly.

**Comment by aabouzaid** [comment]
@kaplun I wish it was available when I started this project :D
I think eventually should move to it.
Thanks a lot for this tip.

@axlroden Never mind, thanks for confirmation :+1:
